### PR TITLE
Add Grid Power Available binary sensor

### PR DESCRIPTION
**Pull request by WillCodeForCats**
Add Grid Power Available binary sensor

### CODE REVIEW

**Comment by WillCodeForCats** [comment]
Info for this entity contributed by @dgilmour77

**Comment by WillCodeForCats** [comment]
Two confirmed OK tests.

**Comment by deqw** [comment]
@WillCodeForCats Is this enhancement now in the 2.4.16 release? Is 2.4.17-pre.3 now the same as 2.4.16?

**Comment by WillCodeForCats** [comment]
I haven't made a 2.4.17 release yet becasue I was waiting to see if there was more test feedback.

**Comment by deqw** [comment]
No problem, still running 2.4.17-pre.3 here. I looked at the Code page and saw the GridStatusOnOff class there. Thought that was the latest release 2.4.16 from a few days ago (but it isn't).

**Comment by WillCodeForCats** [comment]
I can probably just make the release, I was just hoping for more than 2 confirmations.

**Comment by deqw** [comment]
Just wait a little bit longer then. I had some additional questions from SE last week in the case of my questions about the M_Events and the 40113 register. Waiting now again for their response.

Since the 40113 returns 0 (zero) when grid is On and 1 (one) when grid is Off, I'm thinking this undocumented register is related more to the Backup Interface status, like Backup On (1) and Off (0) and not meant for Grid On or Off because for that we have the M-Events already. Just a thought. Hope SE can shed some light into this.

**Comment by WillCodeForCats** [comment]
I just made the release, but if there's more to add I'll just do another one. I'm pretty active about getting things added.

**Pull request merged**
